import { StyleSheet } from 'react-native';
import { colors } from '../../../design/tokens';
import { LIKE_PILL_ACCENT, LIKE_PILL_MUTED } from './constants';

export const styles = StyleSheet.create({
  headerBlock: {
    marginBottom: 14,
    width: '100%',
  },
  headerTextBlock: {
    gap: 4,
  },
  title: {
    fontSize: 18,
    fontWeight: '800',
    color: 'rgba(3, 3, 3, 0.59)',
    letterSpacing: 2,
  },
  titleNight: {
    color: 'rgba(255, 255, 255, 0.92)',
  },
  hintText: {
    fontSize: 14,
    color: 'rgba(26, 26, 26, 0.47)',
    marginTop: 6,
    lineHeight: 15,
  },
  hintTextNight: {
    color: 'rgba(255, 255, 255, 0.78)',
  },
  metaText: {
    fontSize: 12,
    fontWeight: '700',
    color: 'rgba(26, 26, 26, 0.42)',
    marginTop: 4,
  },
  metaTextNight: {
    color: 'rgba(255, 255, 255, 0.62)',
  },
  badgePanel: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginBottom: 16,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.32)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.45)',
  },
  badgePanelNight: {
    backgroundColor: 'rgba(255,255,255,0.10)',
    borderColor: 'rgba(255,255,255,0.16)',
  },
  badgePanelText: {
    flex: 1,
    minWidth: 0,
    paddingRight: 12,
  },
  badgeEyebrow: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.1,
    color: 'rgba(26, 26, 26, 0.38)',
  },
  badgeEyebrowNight: {
    color: 'rgba(255, 255, 255, 0.5)',
  },
  badgePanelTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.text,
    marginTop: 2,
  },
  badgePanelTitleNight: {
    color: 'rgba(255,255,255,0.92)',
  },
  badgeWrapper: {
    position: 'relative',
  },
  listHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  listHeaderTitle: {
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 1,
    color: 'rgba(26,26,26,0.54)',
  },
  listHeaderTitleNight: {
    color: 'rgba(255,255,255,0.82)',
  },
  listHeaderMeta: {
    fontSize: 12,
    fontWeight: '700',
    color: 'rgba(26,26,26,0.34)',
  },
  listHeaderMetaNight: {
    color: 'rgba(255,255,255,0.6)',
  },
  trailContainer: {
    position: 'relative',
    width: '100%',
  },
  emptyTrail: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 24,
    gap: 6,
  },
  emptyText: {
    fontSize: 13,
    color: 'rgba(26,26,26,0.40)',
    fontStyle: 'italic',
  },
  memberRow: {
    marginBottom: 12,
    width: '100%',
  },
  doneCheckBadge: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: colors.successBright,
    alignItems: 'center',
    justifyContent: 'center',
  },
  memberCard: {
    flex: 1,
    width: '100%',
    marginTop: 4,
  },
  memberCardContent: {
    paddingHorizontal: 14,
    paddingVertical: 14,
    width: '100%',
  },
  memberHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  memberIdentity: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    paddingRight: 10,
  },
  memberAvatarWrap: {
    width: 38,
    height: 38,
    borderRadius: 50,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 1)',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    marginRight: 12,
    shadowColor: '#4A558F',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  memberAvatarWrapDone: {
    borderColor: colors.successBright,
    backgroundColor: colors.successBright,
  },
  memberAvatar: {
    width: '100%',
    height: '100%',
  },
  memberAvatarInitial: {
    fontSize: 16,
    fontWeight: '700',
    color: '#4A558F',
  },
  memberAvatarInitialDone: {
    color: '#FFFFFF',
  },
  memberName: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '700',
    flex: 1,
  },
  memberCount: {
    fontSize: 14,
    fontWeight: '600',
    color: 'rgba(26,26,26,0.35)',
  },
  goalChips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 10,
  },
  noGoalText: {
    fontSize: 12,
    color: '#A8B2D1',
    fontStyle: 'italic',
  },
  photoSection: {
    marginTop: 12,
    marginBottom: 22,
    paddingLeft: 12,
    overflow: 'hidden',
  },
  photoCarouselClip: {
    width: '100%',
    overflow: 'hidden',
  },
  photoSingleRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
  },
  photoPlaceholderCard: {
    backgroundColor: 'rgba(255,255,255,0.42)',
  },
  photoSlideCard: {
    borderRadius: 24,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.82)',
  },
  photoSlideDashedCard: {
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: 'rgba(26,26,26,0.2)',
    borderTopLeftRadius: 22,
    borderBottomLeftRadius: 22,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
    minWidth: 200,
  },
  photoSlideInner: {
    position: 'relative',
    width: '100%',
  },
  photoTag: {
    position: 'absolute',
    top: 12,
    right: 12,
    zIndex: 2,
    backgroundColor: '#fff',
    borderRadius: 4,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  photoTagText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.primary,
  },
  photoImage: {
    width: '100%',
    aspectRatio: 1.18,
    backgroundColor: '#ECE4DA',
  },
  photoFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 16,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: 'rgba(26,26,26,0.06)',
  },
  photoFooterRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flexShrink: 0,
  },
  photoActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
    flexShrink: 1,
  },
  likePill: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(182, 180, 180, 0.2)',
    borderRadius: 999,
    paddingVertical: 5,
    paddingHorizontal: 12,
    gap: 8,
    alignSelf: 'flex-start',
  },
  likePillCount: {
    fontSize: 15,
    fontWeight: '700',
    color: LIKE_PILL_MUTED,
    fontVariant: ['tabular-nums'],
  },
  likePillCountAccent: {
    color: LIKE_PILL_ACCENT,
  },
  feedReactionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexShrink: 1,
  },
  reactionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  reactionSticker: {
    width: 26,
    height: 26,
    borderRadius: 50,
    borderWidth: 1,
    borderColor: '#FFFAF7',
    overflow: 'hidden',
    backgroundColor: '#FFF2EC',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reactionAvatar: {
    width: '100%',
    height: '100%',
  },
  reactionAvatarFallback: {
    backgroundColor: '#555',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reactionMore: {
    minWidth: 28,
    height: 28,
    borderRadius: 14,
    paddingHorizontal: 6,
    marginLeft: 4,
    backgroundColor: 'rgba(255, 107, 61, 0.14)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reactionMoreText: {
    fontSize: 11,
    fontWeight: '800',
    color: colors.primary,
  },
  photoIndexText: {
    fontSize: 12,
    fontWeight: '700',
    color: 'rgba(26,26,26,0.34)',
  },
  summitRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingTop: 4,
    paddingBottom: 4,
    position: 'relative',
  },
  trailNodeSummit: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#FF6B3D',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
    shadowColor: '#FF6B3D',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  summitText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FF6B3D',
    letterSpacing: 0.3,
  },
});
